# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d429f7d1306071744e4fc499fb5ce7eab2a51e16782f1088d2ba1982907b7527ff6e1b4892f295d2b1af6bc3f6b4cd380fde7be8ee764713ba3defec2942de16

test:
  secret_key_base: eb9ecbe571a1e5e86645d7f2da99ecc9974710c8dbef1f88d8b5088f1d7d9feba921627cf1b35e3f52f7662ffc545084a7e62ba56ca40ea2bafc718b19cf8285

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
